require("dotenv").config();

module.exports = {
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
  DISCORD_SERVER_GUILD_ID: process.env.DISCORD_SERVER_GUILD_ID,
  DISCORD_SERVER_APPLICATION_ID: process.env.DISCORD_SERVER_APPLICATION_ID,
};