require("dotenv").config();

module.exports = {
  DISCORD_BOT_TOKEN: process.env.DISCORD_BOT_TOKEN,
  DISCORD_SERVER_GUILD_ID: process.env.DISCORD_SERVER_GUILD_ID,
  DISCORD_SERVER_APPLICATION_ID: process.env.DISCORD_SERVER_APPLICATION_ID,
  DISCORD_SERVER_START_HERE_CHANNEL_ID: process.env.DISCORD_SERVER_START_HERE_CHANNEL_ID,
  RPC_URL: process.env.RPC_URL,
  REQUIRED_MINIMUM_BALANCE: 0.1, // 0.1 XCR,
  APP_URL: process.env.APP_URL,
  JWT_SECRET: process.env.JWT_SECRET
};